ProjetBDDAdminIndexConcept:
    path:     /ProjetBDD/admin/indexConcept
    defaults: { _controller: ProjetBDDAdminBundle:Default:indexConcept}

ProjetBDDAdminBundleCreationConcept :
    path : /ProjetBDD/admin/creation/concept/
    defaults : {_controller : ProjetBDDAdminBundle:Concept:creer}

ProjetBDDAdminBundleModificationConcept :
    path : /ProjetBDD/admin/modification/concept/{nom}
    defaults : {_controller : ProjetBDDAdminBundle:Concept:modification}

ProjetBDDAdminBundleSuppressionConcept :
    path : /ProjetBDD/admin/suppression/concept/{nom}
    defaults : {_controller : ProjetBDDAdminBundle:Concept:supprimer}

# routing des termes :

ProjetBDDAdminIndexTerme:
    path:     /ProjetBDD/admin/indexTerme
    defaults: { _controller: ProjetBDDAdminBundle:Default:indexTerme}

ProjetBDDAdminBundleCreationTerme :
    path : /ProjetBDD/admin/creation/terme
    defaults : {_controller : ProjetBDDAdminBundle:Terme:creer}

ProjetBDDAdminBundleModificationTerme :
    path : /ProjetBDD/admin/modification/terme/{nom}
    defaults : {_controller : ProjetBDDAdminBundle:Terme:modification}

ProjetBDDAdminBundleSuppressionTerme :
    path : /ProjetBDD/admin/suppression/terme/{nom}
    defaults : {_controller : ProjetBDDAdminBundle:Terme:supprimer}