projet_bdd_admin:
    resource: "@ProjetBDDAdminBundle/Resources/config/routing.yml"
    prefix:   /

projet_bdd_general:
    resource: "@ProjetBDDGeneralBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
